require("prototypes.font")
require("prototypes.style")
require("prototypes.hidden")
require("prototypes.signals")
require("prototypes.deployer")
require("prototypes.scanner")
require("prototypes.technology")
